
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.2 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_PMOD_BT2_JA_DEVICE_ID,
		XPAR_PMOD_BT2_JA_BASEADDR,
		XPAR_PMOD_BT2_JA_INTERRUPT_PRESENT,
		XPAR_PMOD_BT2_JA_IS_DUAL
	},
	{
		XPAR_PMOD_BT2_JB_DEVICE_ID,
		XPAR_PMOD_BT2_JB_BASEADDR,
		XPAR_PMOD_BT2_JB_INTERRUPT_PRESENT,
		XPAR_PMOD_BT2_JB_IS_DUAL
	}
};


