#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/media/freedisk2/steve/VmodCAM/VmodCAM_Genesys/DualCam_Genesys_10May2011/proj/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /EDA/Xilinx/12.4/ISE_DS/EDK
NON_CYG_XILINX_EDK_DIR = /EDA/Xilinx/12.4/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex5

DEVICE = xc5vlx50tff1136-1

LANGUAGE = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT =  -lp /media/freedisk2/steve/VmodCAM/VmodCAM_Genesys/DualCam_Genesys_10May2011/

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) -msg __xps/ise/xmsgprops.lst \
                   $(MICROBLAZE_0_LIBG_OPT)

OBSERVE_PAR_OPTIONS = -error yes

TESTAPP_VMODCAM_OUTPUT_DIR = TestApp_VmodCAM
TESTAPP_VMODCAM_OUTPUT = $(TESTAPP_VMODCAM_OUTPUT_DIR)/executable.elf
CYG_TESTAPP_VMODCAM_OUTPUT_DIR = TestApp_VmodCAM
CYG_TESTAPP_VMODCAM_OUTPUT = $(CYG_TESTAPP_VMODCAM_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(TESTAPP_VMODCAM_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(TESTAPP_VMODCAM_OUTPUT) 

ALL_USER_ELF_FILES = $(TESTAPP_VMODCAM_OUTPUT) 

SIM_CMD = xterm -e ./isim_system

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT) -msg __xps/ise/xmsgprops.lst -s isim


LIBRARIES =  \
       microblaze_0/lib/libxil.a 

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = TestApp_VmodCAM_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/mb_plb_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/rs232_uart_0_wrapper.ngc \
implementation/ddr2_sdram_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/mdm_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/dvma_0_wrapper.ngc \
implementation/hdmi_0_wrapper.ngc \
implementation/cam_ctrl_0_wrapper.ngc \
implementation/cam_ctrl_1_wrapper.ngc \
implementation/cam_iic_0_wrapper.ngc \
implementation/cam_iic_1_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

# cygwin path for windows
SDK_EXPORT_DIR = SDK/SDK_Export/hw
CYG_SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
CYG_SYSTEM_HW_HANDOFF = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
CYG_SYSTEM_HW_HANDOFF_BIT = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
CYG_SYSTEM_HW_HANDOFF_BMM = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(CYG_SYSTEM_HW_HANDOFF) $(CYG_SYSTEM_HW_HANDOFF_BIT) $(CYG_SYSTEM_HW_HANDOFF_BMM)

#################################################################
# SOFTWARE APPLICATION TESTAPP_VMODCAM
#################################################################

TESTAPP_VMODCAM_SOURCES = TestApp_VmodCAM/src/cam_ctrl.c TestApp_VmodCAM/src/main.c TestApp_VmodCAM/src/vmodcam_cfg.c 

TESTAPP_VMODCAM_HEADERS = TestApp_VmodCAM/src/cam_ctrl_header.h TestApp_VmodCAM/src/vmodcam_header.h 

TESTAPP_VMODCAM_CC = mb-gcc
TESTAPP_VMODCAM_CC_SIZE = mb-size
TESTAPP_VMODCAM_CC_OPT = -O2
TESTAPP_VMODCAM_CFLAGS = 
TESTAPP_VMODCAM_CC_SEARCH = # -B
TESTAPP_VMODCAM_LIBPATH = -L./microblaze_0/lib/ # -L
TESTAPP_VMODCAM_INCLUDES = -I./microblaze_0/include/  -ITestApp_VmodCAM/src/ # -I
TESTAPP_VMODCAM_LFLAGS = # -l
TESTAPP_VMODCAM_LINKER_SCRIPT = 
TESTAPP_VMODCAM_LINKER_SCRIPT_FLAG = #-T $(TESTAPP_VMODCAM_LINKER_SCRIPT) 
TESTAPP_VMODCAM_CC_DEBUG_FLAG =  -g 
TESTAPP_VMODCAM_CC_PROFILE_FLAG = # -pg
TESTAPP_VMODCAM_CC_GLOBPTR_FLAG= # -mxl-gp-opt
TESTAPP_VMODCAM_MODE = executable
TESTAPP_VMODCAM_LIBG_OPT = -$(TESTAPP_VMODCAM_MODE) microblaze_0
TESTAPP_VMODCAM_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mxl-barrel-shift -mxl-pattern-compare -mcpu=v8.00.b 
TESTAPP_VMODCAM_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
TESTAPP_VMODCAM_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
TESTAPP_VMODCAM_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
TESTAPP_VMODCAM_OTHER_CC_FLAGS= $(TESTAPP_VMODCAM_CC_GLOBPTR_FLAG)  \
                  $(TESTAPP_VMODCAM_CC_START_ADDR_FLAG) $(TESTAPP_VMODCAM_CC_STACK_SIZE_FLAG) $(TESTAPP_VMODCAM_CC_HEAP_SIZE_FLAG)  \
                  $(TESTAPP_VMODCAM_CC_INFERRED_FLAGS)  \
                  $(TESTAPP_VMODCAM_LINKER_SCRIPT_FLAG) $(TESTAPP_VMODCAM_CC_DEBUG_FLAG) $(TESTAPP_VMODCAM_CC_PROFILE_FLAG) 
