
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_BUTTON_DEVICE_ID,
		XPAR_BUTTON_BASEADDR,
		XPAR_BUTTON_INTERRUPT_PRESENT,
		XPAR_BUTTON_IS_DUAL
	},
	{
		XPAR_ENC_SIG_A_DEVICE_ID,
		XPAR_ENC_SIG_A_BASEADDR,
		XPAR_ENC_SIG_A_INTERRUPT_PRESENT,
		XPAR_ENC_SIG_A_IS_DUAL
	},
	{
		XPAR_ENC_SIG_B_DEVICE_ID,
		XPAR_ENC_SIG_B_BASEADDR,
		XPAR_ENC_SIG_B_INTERRUPT_PRESENT,
		XPAR_ENC_SIG_B_IS_DUAL
	}
};


