
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_CAM_IIC_0_DEVICE_ID,
		XPAR_CAM_IIC_0_BASEADDR,
		XPAR_CAM_IIC_0_TEN_BIT_ADR,
		XPAR_CAM_IIC_0_GPO_WIDTH
	},
	{
		XPAR_CAM_IIC_1_DEVICE_ID,
		XPAR_CAM_IIC_1_BASEADDR,
		XPAR_CAM_IIC_1_TEN_BIT_ADR,
		XPAR_CAM_IIC_1_GPO_WIDTH
	}
};


